#单节点的配置方式
spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
#    eureka职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
#    代表不向注册中心注册自己
    register-with-eureka: false
#    定义eureka的访问路径
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#eureka服务的集群配置方式
#---
#spring:
#  application:
#    name: eureka-server
#  profiles: server1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: server1
##    是否使用IP地址进行集群（默认为false），使用同一个地址会报错
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/
#
#---
#spring:
#  application:
#    name: eureka-server
#  profiles: server1
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: server2
#    #    是否使用IP地址进行集群（默认为false），使用同一个地址会报错
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/
#
#---
#spring:
#  application:
#    name: eureka-server
#  profiles: server3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: server1
#    #    是否使用IP地址进行集群（默认为false），使用同一个地址会报错
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
